<?php
    namespace app\api\controller;
    use app\BaseController;
    //不用验证的页面继承他
    class ApiBase extends BaseController
    {
        public function initialize()
        {
            parent::initialize(); // TODO: Change the autogenerated stub
        }
    }
